# Generated by Django 5.2 on 2025-05-13 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.IntegerField(choices=[(1, 'Thanh toán tiền mặt'), (2, 'Thanh toán online')], default=1),
        ),
    ]
