# Generated by Django 5.2 on 2025-04-24 11:38

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0002_category_product_role_user_avatar_user_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=cloudinary.models.CloudinaryField(blank=True, default='default_avatar_public_id', max_length=255, null=True, verbose_name='image'),
        ),
    ]
