# Generated by Django 5.2 on 2025-05-02 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0006_remove_user_role_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verified_seller',
            field=models.BooleanField(default=False),
        ),
    ]
