# Generated by Django 5.2 on 2025-05-02 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0008_alter_conversation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[(1, 'Thanh toán tiền mặt'), (2, 'Thanh toán online')], default=1, max_length=15),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Đang chờ'), ('completed', 'Đã thanh toán'), ('failed', 'Thanh toán thất bại')], default='pending', max_length=15),
        ),
    ]
