# Generated by Django 5.2 on 2025-05-02 16:53

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0010_alter_order_total_price_alter_orderdetail_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='avatar',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image'),
        ),
    ]
