# Generated by Django 5.2 on 2025-05-02 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0011_shop_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, related_name='shops', to='commerce.product'),
        ),
    ]
